Dev
TheShadowGamer/Invite-Manager pull request #2
Opened 2020-11-18 13:55 UTC by DarkPheonix2122

its not fully finished, gotta add the plugins and stuff, but its good

2020-11-18 13:56 UTC, DarkPheonix2122 commented
Good so far 😁

2020-12-29 00:43 UTC, TheShadowGamer requested changes
I’m just now reviewing this PR.
I have these questions/changes, then I will continue to review the PR.

2020-12-29 00:43 UTC, TheShadowGamer commented on README.md
> +It is your responsibility to make sure your use of this bot is not against the TOS of any services it uses.
What is the difference here

2020-12-29 00:43 UTC, TheShadowGamer commented on dashboard/package.json
> +  "name": "@julianyaman/discord-bot-dashboard",
Wait so you did not make this?

2020-12-29 00:43 UTC, TheShadowGamer commented on dashboard/package.json
> +  "dependencies": {
These should be in the main package.json

2020-12-29 00:43 UTC, TheShadowGamer commented on dashboard/test.js
> +/*****
This file should not exist. The dashboard part should be included in the main index.js.

2021-02-04 03:48 UTC, TheShadowGamer commented
Seeing as ive had no response from @DarkPheonix2122, I’m going to close this.

2021-02-04 03:48 UTC, closed without merging